#pragma once

#include <vulkan/vulkan.h>

namespace VkWrap {

extern PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr_;
extern PFN_vkCreateInstance vkCreateInstance_;
extern PFN_vkCreateDevice vkCreateDevice_;
extern PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr_;
extern PFN_vkCreateSwapchainKHR vkCreateSwapchainKHR_;
extern PFN_vkDestroySwapchainKHR vkDestroySwapchainKHR_;
extern PFN_vkGetSwapchainImagesKHR vkGetSwapchainImagesKHR_;
extern PFN_vkQueuePresentKHR vkQueuePresentKHR_;
extern PFN_vkCreateImageView vkCreateImageView_;
extern PFN_vkDestroyImageView vkDestroyImageView_;
extern PFN_vkCreateRenderPass vkCreateRenderPass_;
extern PFN_vkDestroyRenderPass vkDestroyRenderPass_;
extern PFN_vkCreateFramebuffer vkCreateFramebuffer_;
extern PFN_vkDestroyFramebuffer vkDestroyFramebuffer_;
extern PFN_vkCreateCommandPool vkCreateCommandPool_;
extern PFN_vkResetCommandPool vkResetCommandPool_;
extern PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers_;
extern PFN_vkBeginCommandBuffer vkBeginCommandBuffer_;
extern PFN_vkEndCommandBuffer vkEndCommandBuffer_;
extern PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass_;
extern PFN_vkCmdEndRenderPass vkCmdEndRenderPass_;
extern PFN_vkQueueSubmit vkQueueSubmit_;
extern PFN_vkCreateFence vkCreateFence_;
extern PFN_vkWaitForFences vkWaitForFences_;
extern PFN_vkResetFences vkResetFences_;
extern PFN_vkDestroyFence vkDestroyFence_;
extern PFN_vkCreateSemaphore vkCreateSemaphore_;
extern PFN_vkDestroySemaphore vkDestroySemaphore_;
extern PFN_vkCreateDescriptorPool vkCreateDescriptorPool_;
extern PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties_;
extern PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties_;
extern PFN_vkDeviceWaitIdle vkDeviceWaitIdle_;

bool Load();
void ResolveInstanceFunctions(VkInstance instance);
void ResolveDeviceFunctions(VkDevice device);

}
